[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "axi"
version = "0.0.0a1"
authors = [{ name = "Axi" }]
requires-python = ">=3.8"
keywords = []
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]
readme = "README.md"

[project.urls]
Repository = "https://pypi.org/project/axi/"
Documentation = "https://pypi.org/project/axi/"
Changelog = "https://pypi.org/project/axi/"

[tool.maturin]
bindings = "bin"
manifest-path = "crates/axi/Cargo.toml"
module-name = "axi"
python-source = "python"
strip = true
include = ["rust-toolchain.toml"]
