[package]
name = "uv-shell"
version = "0.0.1"
edition = "2021"
description = "Utilities for detecting and manipulating shell environments"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
uv-fs = { workspace = true }
uv-static = { workspace = true }

anyhow = { workspace = true }
home = { workspace = true }
same-file = { workspace = true }
tracing = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-registry = { workspace = true }
windows-result = { workspace = true }
windows-sys = { workspace = true }
