[package]
name = "uv-shell"
version = "0.0.1"
edition = { workspace = true }
description = "Utilities for detecting and manipulating shell environments"
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
uv-fs = { workspace = true }
uv-static = { workspace = true }

anyhow = { workspace = true }
fs-err = { workspace = true }
home = { workspace = true }
same-file = { workspace = true }
tracing = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
windows-registry = { workspace = true }

[dev-dependencies]
fs-err = { workspace = true }
tempfile = { workspace = true }
