[package]
name = "maturin_editable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maturin_editable"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.0"
