[package]
name = "uv-interpreter"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
cache-key = { workspace = true }
install-wheel-rs = { workspace = true }
pep440_rs = { workspace = true }
pep508_rs = { workspace = true, features = ["serde"] }
platform-tags = { workspace = true }
pypi-types = { workspace = true }
uv-cache = { workspace = true }
uv-fs = { workspace = true }

configparser = { workspace = true }
fs-err = { workspace = true, features = ["tokio"] }
once_cell = { workspace = true }
regex = { workspace = true }
rmp-serde = { workspace = true }
same-file = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
which = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
anyhow = { version = "1.0.80" }
indoc = { version = "2.0.4" }
insta = { version = "1.36.1" }
itertools = { version = "0.12.1" }
tempfile = { version = "3.9.0" }
