[package]
name = "uv-scripts"
version = "0.0.1"
edition = "2021"
description = "Parse PEP 723-style Python scripts."

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true }
uv-pypi-types = { workspace = true }
uv-settings = { workspace = true }
uv-workspace = { workspace = true }

fs-err = { workspace = true, features = ["tokio"] }
indoc = { workspace = true }
memchr = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
