[package]
name = "uv-normalize"
version = "0.0.1"
edition = "2021"
description = "Normalization for distribution, package and extra names."

[lints]
workspace = true

[dependencies]
rkyv = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
