[package]
name = "uv-errors"
version = "0.0.24"
description = "Common error traits for uv."
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
owo-colors = { workspace = true }

[lints]
workspace = true
