[package]
name = "uv-console"
version = "0.0.1"
edition = "2021"
description = "Utilities for interacting with the terminal"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
console = { workspace = true }
