[package]
name = "puffin-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puffin-requirements = { path = "../puffin-requirements" }
puffin-client = { path = "../puffin-client" }

anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
colored = { version = "2.0.4" }
memchr = { version = "2.6.4" }
async-std = { version = "1.12.0", features = [
    "attributes",
    "tokio1",
    "unstable",
] }
