[package]
name = "uv-install-wheel"
version = "0.0.24"
description = "This is an internal component crate of uv"
keywords = ["wheel", "python"]

edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
name = "uv_install_wheel"

[dependencies]
uv-distribution-filename = { workspace = true }
uv-flags = { workspace = true }
uv-fs = { workspace = true }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-preview = { workspace = true }
uv-pypi-types = { workspace = true }
uv-shell = { workspace = true }
uv-trampoline-builder = { workspace = true }
uv-warnings = { workspace = true }

clap = { workspace = true, optional = true, features = ["derive"] }
configparser = { workspace = true }
csv = { workspace = true }
data-encoding = { workspace = true }
fs-err = { workspace = true }
itertools = { workspace = true }
mailparse = { workspace = true }
owo-colors = { workspace = true }
pathdiff = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
same-file = { workspace = true }
self-replace = { workspace = true }

[features]
clap = ["dep:clap", "uv-fs/clap"]
schemars = ["dep:schemars", "uv-fs/schemars"]

[dev-dependencies]
anyhow = { workspace = true }
assert_fs = { workspace = true }
indoc = { workspace = true }
