[project]
name = "torch-user"
version = "1.0.0"
requires-python = "==3.13.*"
dependencies = ["torch"]

[[tool.uv.index]]
name = "torch-variants"
url = "https://download.pytorch.org/whl/variant"
default = true

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"
