[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = ["anyio"]

[tool.uv.sources]
anyio = { git = "https://github.com/agronholm/anyio", rev = "64b753b19c9a49e3ae395cde457cf82d51f7e999" }
