[package]
name = "uv-globfilter"
version = "0.0.24"
description = "This is an internal component crate of uv"
readme = "README.md"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
globset = { workspace = true }
owo-colors = { workspace = true }
regex = { workspace = true }
regex-automata = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
anstream = { workspace = true }
fs-err = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
