[package]
name = "uv-pubgrub"
version = "0.0.1"
edition = "2021"
description = "Common uv pubgrub types."

[lints]
workspace = true

[dependencies]
uv-pep440 = { workspace = true }

itertools = { workspace = true }
thiserror = { workspace = true }
pubgrub = { workspace = true }
