[package]
name = "uv-settings"
version = "0.0.24"
description = "This is an internal component crate of uv"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
uv-cache-info = { workspace = true, features = ["schemars"] }
uv-client = { workspace = true }
uv-configuration = { workspace = true, features = ["schemars", "clap"] }
uv-dirs = { workspace = true }
uv-distribution-types = { workspace = true, features = ["schemars"] }
uv-flags = { workspace = true }
uv-fs = { workspace = true }
uv-install-wheel = { workspace = true, features = ["schemars", "clap"] }
uv-macros = { workspace = true }
uv-normalize = { workspace = true, features = ["schemars"] }
uv-options-metadata = { workspace = true }
uv-pep508 = { workspace = true }
uv-pypi-types = { workspace = true }
uv-python = { workspace = true, features = ["schemars", "clap"] }
uv-redacted = { workspace = true }
uv-resolver = { workspace = true, features = ["schemars", "clap"] }
uv-static = { workspace = true }
uv-torch = { workspace = true, features = ["schemars", "clap"] }
uv-warnings = { workspace = true }
uv-workspace = { workspace = true, features = ["schemars", "clap"] }

clap = { workspace = true }
fs-err = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
textwrap = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["uv-options-metadata", "clap"]

[dev-dependencies]

[features]
tracing-durations-export = []
