[package]
name = "uv-build-backend"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
uv-distribution-filename = { workspace = true }
uv-fs = { workspace = true }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true }
uv-pubgrub = { workspace = true }
uv-pypi-types = { workspace = true }
uv-version = { workspace = true }
uv-warnings = { workspace = true }

csv = { workspace = true}
fs-err = { workspace = true }
glob = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
spdx = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
indoc = { version = "2.0.5" }
insta = { version = "1.40.0", features = ["filters"] }
tempfile = { version = "3.12.0" }
