[package]
name = "uv-cli"
version = "0.0.1"
description = "The command line interface for the uv binary."
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
distribution-types = { workspace = true }
install-wheel-rs = { workspace = true, features = ["clap"], default-features = false }
pep508_rs = { workspace = true }
pypi-types = { workspace = true }
uv-cache = { workspace = true, features = ["clap"] }
uv-configuration = { workspace = true, features = ["clap"] }
uv-normalize = { workspace = true }
uv-python = { workspace = true, features = ["clap", "schemars"]}
uv-resolver = { workspace = true, features = ["clap"] }
uv-settings = { workspace = true, features = ["schemars"] }
uv-version = { workspace = true }
uv-warnings = { workspace = true }

anstream = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "string"] }
clap_complete_command = { workspace = true }
serde = { workspace = true }
url = { workspace = true }

[dev-dependencies]
insta = { version = "1.40.0", features = ["filters", "json"] }

[features]
default = []
self-update = []

[build-dependencies]
fs-err = { workspace = true }
