# Publish a release to crates.io.
#
# Assumed to run as a subworkflow of .github/workflows/release.yml; specifically, as a publish job
# within `cargo-dist`.
name: "Publish to crates.io"

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  crates-publish-uv:
    name: Upload uv to crates.io
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: read
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            persist-credentials: false
        # TODO(zanieb): Switch to trusted publishing once published
        # - uses: rust-lang/crates-io-auth-action@v1
        #   id: auth
        - name: "Install uv"
          uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
          with:
            version: "0.9.8"    
        - name: Publish workspace crates
          run: |
            for crate in $(uv run ./scripts/list-crates.py); do
              echo "Publishing $crate"
              cargo publish -p $crate
            done
          env:
            CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
